/**
 * Shared OVIO styles.
 * Use these styles for the extracted OVIO building blocks instead of restyling each file.
 */
import { StyleSheet } from "react-native";

import { ovioColors } from "@/design/tokens/colors";
import { ovioLayout } from "@/design/tokens/layout";
import { ovioRadius } from "@/design/tokens/radius";
import { ovioSpacing } from "@/design/tokens/spacing";

// This one style sheet keeps the extracted OVIO components visually in sync.
export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: ovioColors.backgroundCanvas,
  },
  phoneFrame: {
    flex: 1,
    backgroundColor: ovioColors.backgroundCanvas,
  },
  headerContainer: {
    paddingTop: ovioLayout.screenHeaderTopPadding,
    paddingHorizontal: ovioLayout.screenHorizontalPadding,
  },
  scroll: {
    flex: 1,
  },
  content: {
    paddingHorizontal: ovioLayout.screenHorizontalPadding,
    paddingBottom: ovioLayout.screenContentBottomPadding,
  },
  divider: {
    height: 1,
    backgroundColor: "#d5d5d5",
    marginTop: 10,
    marginBottom: 12,
  },
  sectionLabel: {
    marginTop: 8,
    marginBottom: 8,
    fontSize: 10,
    letterSpacing: 3,
    fontWeight: "800",
    color: "#7f7f7f",
  },
  statCard: {
    flex: 1,
    backgroundColor: ovioColors.backgroundSurface,
    borderRadius: ovioRadius[18],
    paddingHorizontal: ovioSpacing[14],
    paddingVertical: ovioSpacing[14],
  },
  statLabel: {
    fontSize: 9,
    letterSpacing: 0.6,
    fontWeight: "700",
    color: "#9c9c9c",
  },
  statValue: {
    marginTop: 8,
    fontSize: 42,
    letterSpacing: -1.5,
    fontWeight: "900",
    color: "#070707",
  },
  recordCard: {
    backgroundColor: ovioColors.backgroundCard,
    borderRadius: ovioRadius[18],
    minHeight: 75,
    paddingVertical: ovioSpacing[10],
    paddingLeft: ovioSpacing[14],
    paddingRight: ovioSpacing[14],
    marginBottom: ovioSpacing[10],
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#ececec",
    shadowColor: ovioColors.shadowBase,
    shadowOpacity: 0.05,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 1,
  },
  recordCardActive: {
    backgroundColor: "#e4e4e4",
  },
  recordContent: {
    gap: 12,
  },
  recordTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  recordTitle: {
    flexShrink: 1,
    fontSize: 16,
    lineHeight: 16,
    letterSpacing: -0.5,
    fontWeight: "900",
    color: "#0c0c0c",
  },
  soundTypeBadge: {
    borderRadius: 5,
    borderWidth: 1,
    borderColor: "#d2d2d2",
    backgroundColor: "#f1f1f1",
    paddingHorizontal: 6,
    paddingVertical: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  soundTypeText: {
    fontSize: 8,
    lineHeight: 8,
    includeFontPadding: false,
    letterSpacing: 0.6,
    fontWeight: "800",
    color: "#666666",
  },
  recordMeta: {
    fontSize: 12,
    letterSpacing: 0.6,
    fontWeight: "600",
    color: "#8b8b8b",
  },
  recordMetaRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  recordLikeIndicator: {
    marginLeft: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  swipeActions: {
    width: ovioLayout.swipeActionsWidth,
    marginBottom: ovioSpacing[10],
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: ovioSpacing[8],
    overflow: "hidden",
  },
  swipeActionButton: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: "#141414",
    alignItems: "center",
    justifyContent: "center",
  },
  swipeActionButtonDelete: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: "#d13d3d",
    alignItems: "center",
    justifyContent: "center",
  },
  rowCard: {
    backgroundColor: ovioColors.backgroundSurface,
    borderRadius: ovioRadius[14],
    minHeight: 50,
    paddingHorizontal: ovioSpacing[14],
    marginBottom: ovioSpacing[10],
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  rowLabel: {
    fontSize: 13,
    letterSpacing: 0.2,
    fontWeight: "800",
    color: "#111",
  },
  rowValue: {
    fontSize: 12,
    letterSpacing: 0.2,
    fontWeight: "800",
    color: "#315ee9",
  },
  toggleTrack: {
    width: 46,
    height: 26,
    borderRadius: 13,
    backgroundColor: "#101010",
    justifyContent: "center",
    paddingHorizontal: 3,
    alignItems: "flex-end",
  },
  toggleThumb: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: "#fff",
  },
  premiumCard: {
    marginTop: 2,
    backgroundColor: "#070707",
    borderRadius: ovioRadius[24],
    padding: ovioSpacing[18],
    minHeight: 148,
    overflow: "hidden",
  },
  premiumTitle: {
    fontSize: 36,
    fontWeight: "900",
    letterSpacing: -1.2,
    color: "#fff",
  },
  premiumSubtitle: {
    marginTop: 4,
    fontSize: 11,
    letterSpacing: 1.4,
    fontWeight: "700",
    color: "#8f8f8f",
  },
  premiumButton: {
    marginTop: ovioSpacing[18],
    alignSelf: "flex-start",
    backgroundColor: ovioColors.backgroundRaised,
    borderRadius: 13,
    paddingHorizontal: ovioSpacing[14],
    paddingVertical: 9,
  },
  premiumButtonText: {
    fontSize: 11,
    letterSpacing: 1,
    fontWeight: "800",
    color: "#101010",
  },
  premiumOrb: {
    position: "absolute",
    width: 120,
    height: 120,
    borderRadius: 60,
    right: -22,
    bottom: -32,
    backgroundColor: "#16181b",
  },
  miniPlayerWrap: {
    position: "absolute",
    left: ovioLayout.screenHorizontalPadding,
    right: ovioLayout.screenHorizontalPadding,
    borderRadius: ovioRadius[24],
    overflow: "hidden",
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.3)",
    shadowColor: ovioColors.shadowBase,
    shadowOpacity: 0.14,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 10,
  },
  miniPlayerBlur: {
    minHeight: 80,
    paddingVertical: ovioSpacing[10],
    paddingLeft: ovioSpacing[10],
    paddingRight: ovioSpacing[12],
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.17)",
  },
  miniPlayerTextWrap: {
    flex: 1,
    marginLeft: ovioSpacing[12],
    marginRight: ovioSpacing[12],
    gap: 2,
  },
  miniPlayerContentRow: {
    flex: 1,
    marginLeft: ovioSpacing[12],
    marginRight: ovioSpacing[12],
    flexDirection: "row",
    alignItems: "center",
    minWidth: 0,
  },
  miniPlayerTextBlock: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  miniPlayerRightGroup: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  miniPlayerTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  miniPlayerTitle: {
    flex: 1,
    flexShrink: 1,
    fontSize: 14,
    letterSpacing: -0.2,
    fontWeight: "800",
    color: "#101010",
  },
  miniPlayerSubtitle: {
    fontSize: 11,
    letterSpacing: 0.2,
    fontWeight: "600",
    color: "rgba(17, 17, 17, 0.56)",
  },
  miniPlayerWaveform: {
    height: 18,
    flexDirection: "row",
    alignItems: "center",
    gap: 2,
  },
  miniPlayerWaveformBar: {
    width: 2,
    borderRadius: 999,
    backgroundColor: "rgba(17, 17, 17, 0.68)",
  },
  miniPlayerButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255, 255, 255, 0.34)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.42)",
  },
  bottomNav: {
    position: "absolute",
    left: ovioLayout.screenBottomInset,
    right: ovioLayout.screenBottomInset,
    bottom: ovioLayout.screenBottomInset,
    backgroundColor: ovioColors.black,
    borderRadius: 28,
    minHeight: 56,
    padding: 6,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  navButtonActive: {
    width: 60,
    height: 44,
    borderRadius: 22,
    backgroundColor: ovioColors.backgroundRaised,
    alignItems: "center",
    justifyContent: "center",
  },
  navButton: {
    width: 60,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
  },
  navIconActive: {
    fontSize: 12,
    letterSpacing: 0.8,
    color: "#050505",
    fontWeight: "800",
  },
  navIcon: {
    fontSize: 12,
    letterSpacing: 0.8,
    color: ovioColors.textMutedDim,
    fontWeight: "700",
  },
});
